version: '2'
services:
  web:
    build: web
    ports:
    - "80:5000"
    volumes:
    - .:/app
    depends_on:
    - sass
  dev:
    build: web
    ports:
    - "80:80"
    volumes:
    - ./web:/app
    - ./analysis:/app/analysis
    - ~/stalker:/root/stalker
    environment:
    - FLASK_DEBUG=1
    - TZ=Europe/Prague
    command: python3 web.py
    depends_on:
    - sass_watch
  sass:
    image: ubuntudesign/sass
    volumes:
    - ./web/static/css/:/app
    command: sass /app/style.scss style.css
  sass_watch:
    image: ubuntudesign/sass
    volumes:
    - ./web/static/css/:/app
    command: sass --watch /app

